set_property PACKAGE_PIN H18 [get_ports {led[3]}]
set_property PACKAGE_PIN J18 [get_ports {led[2]}]
set_property PACKAGE_PIN K14 [get_ports {led[1]}]
set_property PACKAGE_PIN J14 [get_ports {led[0]}]
set_property PACKAGE_PIN M15 [get_ports {key[0]}]
set_property PACKAGE_PIN M14 [get_ports {key[1]}]
set_property PACKAGE_PIN L17 [get_ports {key[2]}]
set_property PACKAGE_PIN L16 [get_ports {key[3]}]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_ports sys_clk]

